# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mauricio Alvarez
email: malvape1595@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ingeniero industrial y de sistemas de la Universidad de Piura.

url: https://malvape.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl:  /myweb # the subpath of your site, e.g. "/blog"
locale: "es-ES"

# No GitHub API authentication could be found. Some fields may be missing or have incorrect data. esto se soluciona
# descargando un permiso y señalandolo en configuration https://www.youtube.com/watch?v=1bQqkyvH5ps

twitter_username: MauricioALQ
github_username: Malvape
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
#repository: Malvape/myweb
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone:  America/Lima

og_image: /assets/images/default.jpg
teaser: /assets/images/default.jpg


include:
  - _pages


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mauricio Alvarez"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Ingeniero industrial y de sistemas de la Universidad de Piura."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://malvape.github.io/myweb/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MauricioALQ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Malvape"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mauricioalvarezq/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:malvape1595@hotmail.com"


#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://malvape.github.io/myweb/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MauricioALQ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mauricioalvarezq/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:malvape1595@hotmail.com"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# SEO Related
google_site_verification : "google-site-verification=1jo-tJbPMyczon7YbmdKRIjsoz_jYymA9Lqz3a4yAGU"

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : G-611CJE92B9
    anonymize_ip         :

  # Necesario

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
